# Generated by Django 4.2.6 on 2023-10-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_description1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_description2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_description3',
        ),
    ]
